// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/detector.proto

package detectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectorService_Detect_FullMethodName = "/detector.DetectorService/Detect"
)

// DetectorServiceClient is the client API for DetectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectorServiceClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type detectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorServiceClient(cc grpc.ClientConnInterface) DetectorServiceClient {
	return &detectorServiceClient{cc}
}

func (c *detectorServiceClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, DetectorService_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectorServiceServer is the server API for DetectorService service.
// All implementations must embed UnimplementedDetectorServiceServer
// for forward compatibility.
type DetectorServiceServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	mustEmbedUnimplementedDetectorServiceServer()
}

// UnimplementedDetectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectorServiceServer struct{}

func (UnimplementedDetectorServiceServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectorServiceServer) mustEmbedUnimplementedDetectorServiceServer() {}
func (UnimplementedDetectorServiceServer) testEmbeddedByValue()                         {}

// UnsafeDetectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectorServiceServer will
// result in compilation errors.
type UnsafeDetectorServiceServer interface {
	mustEmbedUnimplementedDetectorServiceServer()
}

func RegisterDetectorServiceServer(s grpc.ServiceRegistrar, srv DetectorServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectorService_ServiceDesc, srv)
}

func _DetectorService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectorService_ServiceDesc is the grpc.ServiceDesc for DetectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detector.DetectorService",
	HandlerType: (*DetectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectorService_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/detector.proto",
}
