// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/detector.proto

package detectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_proto_detector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_proto_detector_proto_rawDescGZIP(), []int{0}
}

func (x *DetectRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DetectRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *DetectRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type DetectResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReceivedSourceId string                 `protobuf:"bytes,3,opt,name=received_source_id,json=receivedSourceId,proto3" json:"received_source_id,omitempty"`
	ReceivedPayload  string                 `protobuf:"bytes,4,opt,name=received_payload,json=receivedPayload,proto3" json:"received_payload,omitempty"`
	ProcessedAtMs    int64                  `protobuf:"varint,5,opt,name=processed_at_ms,json=processedAtMs,proto3" json:"processed_at_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_proto_detector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_proto_detector_proto_rawDescGZIP(), []int{1}
}

func (x *DetectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DetectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DetectResponse) GetReceivedSourceId() string {
	if x != nil {
		return x.ReceivedSourceId
	}
	return ""
}

func (x *DetectResponse) GetReceivedPayload() string {
	if x != nil {
		return x.ReceivedPayload
	}
	return ""
}

func (x *DetectResponse) GetProcessedAtMs() int64 {
	if x != nil {
		return x.ProcessedAtMs
	}
	return 0
}

var File_proto_detector_proto protoreflect.FileDescriptor

const file_proto_detector_proto_rawDesc = "" +
	"\n" +
	"\x14proto/detector.proto\x12\bdetector\"i\n" +
	"\rDetectRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\xbb\x01\n" +
	"\x0eDetectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x12received_source_id\x18\x03 \x01(\tR\x10receivedSourceId\x12)\n" +
	"\x10received_payload\x18\x04 \x01(\tR\x0freceivedPayload\x12&\n" +
	"\x0fprocessed_at_ms\x18\x05 \x01(\x03R\rprocessedAtMs2N\n" +
	"\x0fDetectorService\x12;\n" +
	"\x06Detect\x12\x17.detector.DetectRequest\x1a\x18.detector.DetectResponseB\x19Z\x17api_go/proto/detectorpbb\x06proto3"

var (
	file_proto_detector_proto_rawDescOnce sync.Once
	file_proto_detector_proto_rawDescData []byte
)

func file_proto_detector_proto_rawDescGZIP() []byte {
	file_proto_detector_proto_rawDescOnce.Do(func() {
		file_proto_detector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_detector_proto_rawDesc), len(file_proto_detector_proto_rawDesc)))
	})
	return file_proto_detector_proto_rawDescData
}

var file_proto_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_detector_proto_goTypes = []any{
	(*DetectRequest)(nil),  // 0: detector.DetectRequest
	(*DetectResponse)(nil), // 1: detector.DetectResponse
}
var file_proto_detector_proto_depIdxs = []int32{
	0, // 0: detector.DetectorService.Detect:input_type -> detector.DetectRequest
	1, // 1: detector.DetectorService.Detect:output_type -> detector.DetectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_detector_proto_init() }
func file_proto_detector_proto_init() {
	if File_proto_detector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_detector_proto_rawDesc), len(file_proto_detector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_detector_proto_goTypes,
		DependencyIndexes: file_proto_detector_proto_depIdxs,
		MessageInfos:      file_proto_detector_proto_msgTypes,
	}.Build()
	File_proto_detector_proto = out.File
	file_proto_detector_proto_goTypes = nil
	file_proto_detector_proto_depIdxs = nil
}
