# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65tector.proto\x12\x08\x64\x65tector\"I\n\rDetectRequest\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"|\n\x0e\x44\x65tectResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12received_source_id\x18\x03 \x01(\t\x12\x18\n\x10received_payload\x18\x04 \x01(\t\x12\x17\n\x0fprocessed_at_ms\x18\x05 \x01(\x03\x32N\n\x0f\x44\x65tectorService\x12;\n\x06\x44\x65tect\x12\x17.detector.DetectRequest\x1a\x18.detector.DetectResponseB\x19Z\x17\x61pi_go/proto/detectorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027api_go/proto/detectorpb'
  _globals['_DETECTREQUEST']._serialized_start=28
  _globals['_DETECTREQUEST']._serialized_end=101
  _globals['_DETECTRESPONSE']._serialized_start=103
  _globals['_DETECTRESPONSE']._serialized_end=227
  _globals['_DETECTORSERVICE']._serialized_start=229
  _globals['_DETECTORSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
