"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import detector_pb2 as _detector_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DetectorServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DetectorServiceAsyncStub: ...
    Detect: _grpc.UnaryUnaryMultiCallable[_detector_pb2.DetectRequest, _detector_pb2.DetectResponse]

@_typing.type_check_only
class DetectorServiceAsyncStub(DetectorServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Detect: _aio.UnaryUnaryMultiCallable[_detector_pb2.DetectRequest, _detector_pb2.DetectResponse]  # type: ignore[assignment]

class DetectorServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Detect(
        self,
        request: _detector_pb2.DetectRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_detector_pb2.DetectResponse, _abc.Awaitable[_detector_pb2.DetectResponse]]: ...

def add_DetectorServiceServicer_to_server(servicer: DetectorServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
