"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DetectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    source_id: _builtins.str
    payload: _builtins.str
    timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        source_id: _builtins.str = ...,
        payload: _builtins.str = ...,
        timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "source_id", b"source_id", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetectRequest: _TypeAlias = DetectRequest  # noqa: Y015

@_typing.final
class DetectResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    RECEIVED_SOURCE_ID_FIELD_NUMBER: _builtins.int
    RECEIVED_PAYLOAD_FIELD_NUMBER: _builtins.int
    PROCESSED_AT_MS_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    message: _builtins.str
    received_source_id: _builtins.str
    received_payload: _builtins.str
    processed_at_ms: _builtins.int
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
        message: _builtins.str = ...,
        received_source_id: _builtins.str = ...,
        received_payload: _builtins.str = ...,
        processed_at_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "ok", b"ok", "processed_at_ms", b"processed_at_ms", "received_payload", b"received_payload", "received_source_id", b"received_source_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetectResponse: _TypeAlias = DetectResponse  # noqa: Y015
